name: Xcode

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2
      
      - name: Deps
        working-directory: ${{github.workspace}}
        run: python build_deps.py

      - name: Build
        working-directory: ${{github.workspace}}
        run: xcodebuild
