name: Xcode

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: ${{github.workspace}}
        run: xcodebuild
